version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.18.4
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - restore_cache:
          key: -app-{{ checksum "package.json" }}
            -app-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.json" }}

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: staging 
